package dns

var products = map[string][]string{
	"CloudFront":                 {"cloudfront.net", "cloudfront"},
	"CloudFlare":                 {"cloudflare.com", "cloudflare", "cc-ecdn.net"},
	"Akamai":                     {"akamaitechnologies.com", "edgekey.net", "akamaiedge.net", "akam.net"},
	"Imperva":                    {"incapsula.com"},
	"Sucuri":                     {"sucuri.net"},
	"Bunny":                      {"bunnyinfra.net"},
	"KeyCDN":                     {"proinity.net"},
	"CDN77":                      {"cdn77.com"},
	"AWS Global Accelerator":     {"awsglobalaccelerator.com"},
	"AWS":                        {"amazonaws.com"},
	"Microsoft Office 365":       {"lync.com", "office.com", "outlook.com"},
	"Microsoft Sharepoint":       {"sharepointonline.com"},
	"Azure":                      {"azure-dns.com", "azure-dns.net", "azure-dns.org", "azure-dns.info", "azurewebsites.net"},
	"Locaweb":                    {"locaweb.com.br"},
	"Oracle Cloud":               {"oraclecloud.net"},
	"GCP":                        {"googleusercontent.com"},
	"Heroku":                     {"herokuapp.com", "herokudns.com"},
	"Registro.BR":                {"dns.br"},
	"Trend Micro Email Security": {"tmes.trendmicro.com"},
	"Wix":                        {"wixsite.com", "wixdns.net"},
	"Github":                     {"github.io", "github.com"},
}
