name: Go Install Check

on:
  push:
    branches: [main]
    paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - Dockerfile

  pull_request:
    branches: [main]
    paths-ignore:
        - .gitignore
        - README.md
        - LICENSE
        - TODO
        - Dockerfile

  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ca-certificates jq curl

      - name: Install certcrawler at specific commit
        run: |
          go install github.com/helviojunior/certcrawler@${GITHUB_SHA}

      - name: Create a fake wordlist
        run: |
          cat << EOF > /tmp/enpoint.txt
          40.84.222.149
          185.199.110.153:443
          EOF

          cat << EOF > /tmp/hosts.txt
          sec4us.com.br
          wiki.sec4us.com.br
          github.io
          EOF

      - name: Verify Installation
        run: |
          certcrawler version
          certcrawler crawler file -f /tmp/enpoint.txt -d /tmp/hosts.txt -o /tmp/ssl.txt
          
      - name: Get result
        run: |
          cat /tmp/ssl.txt